// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import react from '@astrojs/react';
import mdx from '@astrojs/mdx';

export default defineConfig({
	site: 'https://neurodesk.org',
	compressHTML: false,
	redirects: {
		'/applications': '/overview/applications/',
		'/developers/add_tool': '/developers/new-tools/',
		'/developers/new_tools/add_tool': '/developers/new-tools/',
		'/developers/new_tools/manual_build': '/developers/new-tools/new-tool/',
		'/getting-started/hosted/bunya': '/getting-started/installations/bunya/',
		'/getting-started/hosted/googlecolab': '/getting-started/hosted/google/',
		'/getting-started/hosted/nectar': '/getting-started/installations/nectar/',
		'/getting-started/linux-and-hpc': '/getting-started/neurocommand/linux-and-hpc/',
		'/getting-started/local/examples': '/getting-started/installations/ubuntu2404/',
		'/getting-started/neurocommand/hpc': '/getting-started/neurocommand/linux-and-hpc/',
		'/getting-started/neurocommand/linux': '/getting-started/neurocommand/linux-and-hpc/',
		'/getting-started/neurocontainers/googlecolab': '/getting-started/hosted/google/',
		'/getting-started/neurodesktop/hpc': '/getting-started/neurocommand/linux-and-hpc/',
		'/getting-started/neurodesktop/nectar': '/getting-started/installations/nectar/',
		'/getting-started/neurodesktop/neurodeskapp': '/getting-started/local/neurodeskapp/',
		'/getting-started/neurodesktop/play': '/getting-started/hosted/play/',
		'/getting-started/neurodesktop/visual-studio-code': '/getting-started/neurocommand/visual-studio-code/',
		'/getting-started/pyneurodesk': '/getting-started/neurocommand/pyneurodesk/',
		'/getting-started/storage': '/getting-started/neurodesktop/storage/',
		'/getting-started/visual-studio-code': '/getting-started/neurocommand/visual-studio-code/',
		'/getting-started/windows': '/getting-started/neurocommand/windows/',
		'/how-to-cite-us': '/overview/how-to-cite-us/',
		'/neurocommand': '/getting-started/neurocommand/',
		'/neurocontainers': '/getting-started/neurocontainers/',
		'/neurocontainers/contribute': '/overview/contribute/',
		'/neurodesktop': '/getting-started/neurodesktop/',
		'/neurodesktop/getting-started/cloud': '/getting-started/neurodesktop/cloud/',
		'/neurodesktop/getting-started/linux': '/getting-started/neurodesktop/linux/',
		'/neurodesktop/getting-started/mac': '/getting-started/neurodesktop/mac/',
		'/neurodesktop/getting-started/nectar': '/getting-started/installations/nectar/',
		'/neurodesktop/getting-started/play': '/getting-started/hosted/play/',
		'/neurodesktop/getting-started/windows': '/getting-started/neurodesktop/windows/',
		'/neurodesktop/release-history': '/overview/release-history/',
		'/neurodesktop/storage': '/getting-started/neurodesktop/storage/',
		'/overview/acknowledgment': '/overview/acknowledgement/',
		'/publications': '/overview/publications/',
		'/static/learning-resources/tutorials/electrophysiology/fieldtrip': '/redirects/tutorials-to-neurodeskedu/',
		'/static/learning-resources/tutorials/functional_imaging/connectomeworkbench': '/redirects/tutorials-to-neurodeskedu/',
		'/support/discussion-forum': '/overview/discussion-forum/',
		'/support/faq': '/overview/faq/',
		'/support/release-history': '/overview/release-history/',
		'/tutorials': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials-electrophysiology/eeg_mne-python': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials-examples': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials-examples/contribute': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials-examples/contribute/contribute-examples': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials-examples/contribute/contribute-tutorials': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials-examples/examples': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials-examples/tutorials': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials-examples/tutorials/electrophysiology': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials-examples/tutorials/electrophysiology/eeg_mne-python': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials-examples/tutorials/electrophysiology/fieldtrip': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials-examples/tutorials/functional_imaging': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials-examples/tutorials/functional_imaging/connectomeworkbench': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials-examples/tutorials/functional_imaging/fmriprep_cvl': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials-examples/tutorials/functional_imaging/mriqc_cvl': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials-examples/tutorials/functional_imaging/physio': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials-examples/tutorials/functional_imaging/physio_batch_workflow': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials-examples/tutorials/functional_imaging/spm': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials-examples/tutorials/multimodal_imaging': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials-examples/tutorials/multimodal_imaging/mfcsc': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials-examples/tutorials/open_data': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials-examples/tutorials/open_data/datalad': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials-examples/tutorials/open_data/osfclient': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials-examples/tutorials/phase_processing': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials-examples/tutorials/phase_processing/qsm': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials-examples/tutorials/phase_processing/swi': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials-examples/tutorials/phase_processing/unwrapping': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials-examples/tutorials/programming': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials-examples/tutorials/programming/conda': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials-examples/tutorials/programming/matlab': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials-examples/tutorials/reproducibility': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials-examples/tutorials/reproducibility/datalad-run': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials-examples/tutorials/spectroscopy': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials-examples/tutorials/spectroscopy/lcmodel': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials-examples/tutorials/spectroscopy/mrsiproc': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials-examples/tutorials/structural_imaging': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials-examples/tutorials/structural_imaging/freesurfer': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials-examples/tutorials/structural_imaging/structuralconnectivity': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials/electrophysiology': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials/electrophysiology/eeg_mne-python': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials/electrophysiology/fieldtrip': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials/functional_imaging': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials/functional_imaging/fmriprep_cvl': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials/functional_imaging/mriqc_cvl': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials/functional_imaging/physio': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials/functional_imaging/physio_batch_workflow': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials/functional_imaging/spm': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials/open_data': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials/open_data/datalad': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials/open_data/osfclient': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials/phase_processing': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials/phase_processing/qsm': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials/phase_processing/swi': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials/phase_processing/unwrapping': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials/programming': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials/programming/conda': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials/programming/matlab': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials/reproducibility': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials/reproducibility/datalad-run': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials/spectroscopy': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials/spectroscopy/lcmodel': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials/spectroscopy/mrsiproc': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials/structural_imaging': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials/structural_imaging/freesurfer': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials/structural_imaging/structuralconnectivity': '/redirects/tutorials-to-neurodeskedu/',
		'/tutorials/tutorial-template': '/developers/documentation/creating-website-content/',
		'docs/getting-started/local/neurodeskapp': '/getting-started/local/neurodeskapp/',
	},
	integrations: [
		starlight({
			title: 'Neurodesk',
			description: 'A community-oriented open-source platform for reproducible neuroimaging analysis.',
			logo: {
				light: './src/assets/neurodesk-wordmark-light.svg',
				dark: './src/assets/neurodesk-wordmark-dark.svg',
				replacesTitle: true,
			},
			favicon: '/favicons/favicon.ico',
			head: [
				{ tag: 'link', attrs: { rel: 'apple-touch-icon', sizes: '180x180', href: '/favicons/apple-touch-icon.png' } },
				{ tag: 'link', attrs: { rel: 'icon', type: 'image/png', sizes: '32x32', href: '/favicons/favicon-32x32.png' } },
				{ tag: 'link', attrs: { rel: 'icon', type: 'image/png', sizes: '16x16', href: '/favicons/favicon-16x16.png' } },
				{ tag: 'link', attrs: { rel: 'manifest', href: '/favicons/site.webmanifest' } },
			],
			social: [
				{ icon: 'github', label: 'GitHub', href: 'https://github.com/NeuroDesk' },
				{ icon: 'linkedin', label: 'LinkedIn', href: 'https://www.linkedin.com/company/neurodesk-org/' },
			],
			editLink: {
				baseUrl: 'https://github.com/NeuroDesk/neurodesk.github.io/edit/main/',
			},
			sidebar: [
				{
					label: 'Overview',
					items: [
						{ label: 'Overview', link: '/overview/' },
						{ label: 'Acknowledgement', link: '/overview/acknowledgement/' },
						{ label: 'Applications', link: '/overview/applications/' },
						{ label: 'Code of conduct', link: '/overview/code-of-conduct/' },
						{ label: 'Discussion forum', link: '/overview/discussion-forum/' },
						{ label: 'Donate', link: '/overview/donate/' },
						{ label: 'How to cite us', link: '/overview/how-to-cite-us/' },
						{ label: 'Metrics', link: '/overview/metrics/' },
						{ label: 'Publications', link: '/overview/publications/' },
						{ label: 'FAQ', link: '/overview/faq/' },
						{ label: 'Release history', link: '/overview/release-history/' },
						{ label: 'Contribute', link: '/overview/contribute/' },
					],
				},
				{
					label: 'Getting started',
					items: [
						{ label: 'Overview', link: '/getting-started/' },
						{
							label: 'Local',
							items: [{ autogenerate: { directory: 'getting-started/local' } }],
						},
						{
							label: 'Hosted',
							items: [{ autogenerate: { directory: 'getting-started/hosted' } }],
						},
						{
							label: 'Neurodesktop',
							items: [{ autogenerate: { directory: 'getting-started/neurodesktop' } }],
						},
						{
							label: 'Neurocommand',
							items: [{ autogenerate: { directory: 'getting-started/neurocommand' } }],
						},
						{
							label: 'Neurocontainers',
							items: [{ autogenerate: { directory: 'getting-started/neurocontainers' } }],
						},
						{
							label: 'Installations',
							items: [{ autogenerate: { directory: 'getting-started/installations' } }],
						},
						{
							label: 'Agents',
							items: [{ autogenerate: { directory: 'getting-started/agents' } }],
						},
					],
				},
				{
					label: 'Developers',
					items: [
						{ label: 'Overview', link: '/developers/' },
						{
							label: 'Architecture',
							items: [
								{ label: 'Overview', link: '/developers/architecture/' },
								{ label: 'Neurodesk components', link: '/developers/architecture/neurodesk-components/' },
								{ label: 'Neurodesk dev', link: '/developers/architecture/neurodesk-dev/' },
								{ label: 'Release process', link: '/developers/architecture/release-process/' },
								{ label: 'Roadmap', link: '/developers/architecture/roadmap/' },
								{ label: 'Transparent Singularity', link: '/developers/architecture/transparent-singularity/' },
								{
									label: 'CVMFS',
									items: [{ autogenerate: { directory: 'developers/architecture/cvmfs' } }],
								},
							],
						},
						{
							label: 'Contributors',
							items: [{ autogenerate: { directory: 'developers/contributors' } }],
						},
						{
							label: 'Designer',
							items: [{ autogenerate: { directory: 'developers/designer' } }],
						},
						{
							label: 'Documentation',
							items: [{ autogenerate: { directory: 'developers/documentation' } }],
						},
						{
							label: 'Interfacing',
							items: [{ autogenerate: { directory: 'developers/interfacing' } }],
						},
						{
							label: 'Neurocontainer copilot',
							items: [{ autogenerate: { directory: 'developers/neurocontainer-copilot' } }],
						},
						{
							label: 'Neurodesk copilot',
							items: [{ autogenerate: { directory: 'developers/neurodesk-copilot' } }],
						},
						{
							label: 'New tools',
							items: [{ autogenerate: { directory: 'developers/new-tools' } }],
						},
					],
				},
				{
					label: 'Contact',
					link: '/contact/',
				},
			],
			customCss: ['./src/styles/custom.css'],
		}),
		react(),
		mdx(),
	],
});
